### ISSUE TITLE
Is there a way to run this on a Custom Firmware Switch?

### ISSUE THREAD

**Issue by nefariouslegion** [mkxp-z/mkxp-z#10]
Title says it all. May be a stupid question but felt like asking. I'm trying to find a way to run Pokemon Infinite Fusion on Switch

**Comment by ghost** [comment]
It'll run on L4T (need to build it yourself). Could potentially run on Android, since someone's obsessed with trying to get it running on that to run OneShot, I think

It'll probably never run directly on Horizon+Atmosphere mainly due to using CRuby, which may as well be impossible to port to anything that isn't a mainstream OS, although if someone took it and made it use mruby instead it could very well be possible at that point
