### ISSUE TITLE
Bump SDL to 2.28

### ISSUE THREAD

**Issue by JeremyRand** [mkxp-z/mkxp-z#17]
SDL 2.28 includes a fix for a blitting bug that broke text rendering in mkxp-z on ppc64le platforms; it would be great to bump mkxp-z to that version so that ppc64le users can stop having to apply an SDL patch. I notice that mkxp-z's SDL dependency was recently downgraded in 290ffe1135142d91a40b8f295a7b8e284f432c9a. Is there any more info on the bug in SDL 2.26 that necessitated the downgrade? E.g. instructions to reproduce, or an issue filed with upstream SDL?

**Comment by ghost** [comment]
I dunno if I'd call it a downgrade rather than "I tried to update it and it made everything blow up so I changed it back", but essentially, it seemed like it wasn't listening to some of the window-related Graphics functions if they were called too soon. That and it appeared to crash at random, at which point I just put it back the way that it was.

I did add a `mkxp-z-2.28.1` branch to the SDL fork a couple of days ago, so you can try building with that instead. The NEON flags are acting up again (maybe it's different from the way I normally turn it all off) so I haven't tried it yet to see if anything was different.

The only reason I really ever forked SDL was to disable -mwindows and hide all of the NEON parts, so if you don't need either of those, a system version of SDL (or really any other one) would work just as well.

**Comment by Splendide-Imaginarius** [comment]
I suspect that fixing this might also fix the CI fails that were introduced by https://github.com/mkxp-z/mkxp-z/pull/24 . I'll give it a try and report back on my findings.
