### ISSUE TITLE
Remove symphony-of-war branch

### ISSUE THREAD

**Issue by Nathan-MV** [mkxp-z/mkxp-z#87]
Needs #69 to be completed

**Comment by Splendide-Imaginarius** [comment]
I suspect that removing that branch would be a GPL violation, since that game was (I assume) distributed with a link to that branch. Is its presence hurting anything?

**Comment by Nathan-MV** [comment]
> I suspect that removing that branch would be a GPL violation, since that game was (I assume) distributed with a link to that branch. Is its presence hurting anything?

Symphony wasn't distributed with a link to that branch, they're already violating the GPL, but once again nobody cares

**Comment by Splendide-Imaginarius** [comment]
> Symphony wasn't distributed with a link to that branch, they're already violating the GPL, but once again nobody cares

Well. Maybe they're already in violation, but I don't want to make that situation any worse than it already is. Leaving the branch there doesn't seem to be hurting anything. I've seen lots of production repos that have far more branches than we do.

**Comment by JaidenAlemni** [comment]
I think this is absolutely unnecessary. There are some insights in that branch given it's a well-known game that actually saw a release. 

Edit: Had no idea about any history between the devs when making this comment, but even so my point stands that I think the commit history is still of value, and agree with Splendide that there are probably license reasons as to why it shouldn't be removed.

**Comment by Nathan-MV** [comment]
> There are some insights in that branch given it's a well-known game that actually saw a release.

Insight on how to downgrade the Ruby version so as not break their shit and on how to make changes to the brand, being a well-known game, there is nothing to do with mkxp-z, if they released it with any other shit it would be the same

Struma has ported everything that would be beneficial for Essentials to the dev branch, the only thing missing is rapidcsv

(For those who haven't missed the whole Discord drama, Symphony is one of the reasons why Struma decided to disappear from existence)

**Comment by Splendide-Imaginarius** [comment]
I think there's some educational/cultural value in seeing how a real-world game used mkxp-z. If I were doing it, I maybe wouldn't have used this repo to store that branch, but it is what it is, and I can't change Struma's decision to use this repo without breaking whatever links exist all over the web, and potentially causing license compliance issues. The branch isn't hurting anyone, just because most users don't need it doesn't mean we should be deleting it. Also Discord drama doesn't need to show up on this issue tracker, please keep the issue tracker drama-free so that collaboration is easier.

Closing this as WONTFIX, but if anyone cares, I do not expect to ever create any game-specific branches on this repo while I'm the maintainer.
